sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_0.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_1.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_2.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_3.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_4.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_5.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_6.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_7.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_8.sbatch
sbatch /scratch/a.hek4/gedi_scw/00_gedi_to_gpkg_and_tile/05_tile_gedi/job_scripts/job_file_9.sbatch
